from __future__ import annotations
from g2opy.g2o import AbstractOptimizationAlgorithmCreator
from g2opy.g2o import AngleAxis
from g2opy.g2o import BaseBinaryEdge_1_double_VertexCam_VertexCam
from g2opy.g2o import BaseBinaryEdge_1_double_VertexSE2_VertexPointXY
from g2opy.g2o import BaseBinaryEdge_2_Vector2D_VertexPointXY_VertexPointXY
from g2opy.g2o import BaseBinaryEdge_2_Vector2D_VertexSBAPointXYZ_VertexCam
from g2opy.g2o import BaseBinaryEdge_2_Vector2D_VertexSBAPointXYZ_VertexSE3Expmap
from g2opy.g2o import BaseBinaryEdge_2_Vector2D_VertexSBAPointXYZ_VertexSim3Expmap
from g2opy.g2o import BaseBinaryEdge_2_Vector2D_VertexSE2_VertexPointXY
from g2opy.g2o import BaseBinaryEdge_3_EdgeGICP_VertexSE3_VertexSE3
from g2opy.g2o import BaseBinaryEdge_3_SE2_VertexSE2_VertexSE2
from g2opy.g2o import BaseBinaryEdge_3_Vector3D_VertexPointXYZ_VertexPointXYZ
from g2opy.g2o import BaseBinaryEdge_3_Vector3D_VertexSBAPointXYZ_VertexCam
from g2opy.g2o import BaseBinaryEdge_3_Vector3D_VertexSBAPointXYZ_VertexSCam
from g2opy.g2o import BaseBinaryEdge_3_Vector3D_VertexSBAPointXYZ_VertexSE3Expmap
from g2opy.g2o import BaseBinaryEdge_3_Vector3D_VertexSE3_VertexPointXYZ
from g2opy.g2o import BaseBinaryEdge_6_Isometry3D_VertexSE3_VertexSE3
from g2opy.g2o import BaseBinaryEdge_6_SE3Quat_VertexCam_VertexCam
from g2opy.g2o import BaseBinaryEdge_6_SE3Quat_VertexSE3Expmap_VertexSE3Expmap
from g2opy.g2o import BaseBinaryEdge_7_Sim3_VertexSim3Expmap_VertexSim3Expmap
from g2opy.g2o import BaseEdge_1_double
from g2opy.g2o import BaseEdge_2_Vector2D
from g2opy.g2o import BaseEdge_3_EdgeGICP
from g2opy.g2o import BaseEdge_3_SE2
from g2opy.g2o import BaseEdge_3_Vector3D
from g2opy.g2o import BaseEdge_3_VelocityMeasurement
from g2opy.g2o import BaseEdge_4_Vector4D
from g2opy.g2o import BaseEdge_6_Isometry3D
from g2opy.g2o import BaseEdge_6_SE3Quat
from g2opy.g2o import BaseEdge_7_Sim3
from g2opy.g2o import BaseMultiEdge_2_Vector2D
from g2opy.g2o import BaseMultiEdge_3_SE2
from g2opy.g2o import BaseMultiEdge_3_Vector3D
from g2opy.g2o import BaseMultiEdge_3_VelocityMeasurement
from g2opy.g2o import BaseMultiEdge_4_Vector4D
from g2opy.g2o import BaseMultiEdge_6_SE3Quat
from g2opy.g2o import BaseRobustKernel
from g2opy.g2o import BaseUnaryEdgeBaseUnaryEdge_2_Vector2D_VertexSE3Expmap
from g2opy.g2o import BaseUnaryEdgeBaseUnaryEdge_3_Vector3D_VertexSE3Expmap
from g2opy.g2o import BaseUnaryEdge_2_Vector2D_VertexSE2
from g2opy.g2o import BaseUnaryEdge_3_SE2_VertexSE2
from g2opy.g2o import BaseUnaryEdge_6_Isometry3D_VertexSE3
from g2opy.g2o import BaseVertex_1_double
from g2opy.g2o import BaseVertex_2_Vector2D
from g2opy.g2o import BaseVertex_3_SE2
from g2opy.g2o import BaseVertex_3_Vector3D
from g2opy.g2o import BaseVertex_4_Vector5d
from g2opy.g2o import BaseVertex_6_Isometry3D
from g2opy.g2o import BaseVertex_6_SBACam
from g2opy.g2o import BaseVertex_6_SE3Quat
from g2opy.g2o import BaseVertex_7_Sim3
from g2opy.g2o import BlockSolverBase
from g2opy.g2o import BlockSolverSE2
from g2opy.g2o import BlockSolverSE3
from g2opy.g2o import BlockSolverSim3
from g2opy.g2o import BlockSolverX
from g2opy.g2o import CameraParameters
from g2opy.g2o import DynamicBaseEdge_VectorXD
from g2opy.g2o import DynamicBaseMultiEdge_VectorXD
from g2opy.g2o import EdgeGICP
from g2opy.g2o import EdgeInverseSim3ProjectXYZ
from g2opy.g2o import EdgeNormal
from g2opy.g2o import EdgePointXY
from g2opy.g2o import EdgePointXYZ
from g2opy.g2o import EdgeProjectP2MC
from g2opy.g2o import EdgeProjectP2MCRight
from g2opy.g2o import EdgeProjectP2MC_Intrinsics
from g2opy.g2o import EdgeProjectP2SC
from g2opy.g2o import EdgeProjectPSI2UV
from g2opy.g2o import EdgeProjectXYZ2UV
from g2opy.g2o import EdgeProjectXYZ2UVU
from g2opy.g2o import EdgeSBACam
from g2opy.g2o import EdgeSBAScale
from g2opy.g2o import EdgeSE2
from g2opy.g2o import EdgeSE2LotsOfXY
from g2opy.g2o import EdgeSE2OdomDifferentialCalib
from g2opy.g2o import EdgeSE2Offset
from g2opy.g2o import EdgeSE2PointXY
from g2opy.g2o import EdgeSE2PointXYBearing
from g2opy.g2o import EdgeSE2PointXYCalib
from g2opy.g2o import EdgeSE2PointXYOffset
from g2opy.g2o import EdgeSE2Prior
from g2opy.g2o import EdgeSE2SensorCalib
from g2opy.g2o import EdgeSE2TwoPointsXY
from g2opy.g2o import EdgeSE2XYPrior
from g2opy.g2o import EdgeSE3
from g2opy.g2o import EdgeSE3Expmap
from g2opy.g2o import EdgeSE3LotsOfXYZ
from g2opy.g2o import EdgeSE3Offset
from g2opy.g2o import EdgeSE3PointXYZ
from g2opy.g2o import EdgeSE3PointXYZDepth
from g2opy.g2o import EdgeSE3PointXYZDisparity
from g2opy.g2o import EdgeSE3Prior
from g2opy.g2o import EdgeSE3ProjectXYZ
from g2opy.g2o import EdgeSE3ProjectXYZOnlyPose
from g2opy.g2o import EdgeSim3
from g2opy.g2o import EdgeSim3ProjectXYZ
from g2opy.g2o import EdgeStereoSE3ProjectXYZ
from g2opy.g2o import EdgeStereoSE3ProjectXYZOnlyPose
from g2opy.g2o import Edge_V_V_GICP
from g2opy.g2o import Edge_XYZ_VSC
from g2opy.g2o import EstimatePropagator
from g2opy.g2o import EstimatePropagatorCost
from g2opy.g2o import EstimatePropagatorCostOdometry
from g2opy.g2o import G2OBatchStatistics
from g2opy.g2o import HyperDijkstra
from g2opy.g2o import HyperGraph
from g2opy.g2o import HyperGraphAction
from g2opy.g2o import Isometry2d
from g2opy.g2o import Isometry3d
from g2opy.g2o import JacobianWorkspace
from g2opy.g2o import LinearSolverCSparseSE2
from g2opy.g2o import LinearSolverCSparseSE3
from g2opy.g2o import LinearSolverCSparseSim3
from g2opy.g2o import LinearSolverCSparseX
from g2opy.g2o import LinearSolverCholmodSE2
from g2opy.g2o import LinearSolverCholmodSE3
from g2opy.g2o import LinearSolverCholmodSim3
from g2opy.g2o import LinearSolverCholmodX
from g2opy.g2o import LinearSolverDenseSE2
from g2opy.g2o import LinearSolverDenseSE3
from g2opy.g2o import LinearSolverDenseSim3
from g2opy.g2o import LinearSolverDenseX
from g2opy.g2o import LinearSolverEigenSE2
from g2opy.g2o import LinearSolverEigenSE3
from g2opy.g2o import LinearSolverEigenSim3
from g2opy.g2o import LinearSolverEigenX
from g2opy.g2o import LinearSolverPCGSE2
from g2opy.g2o import LinearSolverPCGSE3
from g2opy.g2o import LinearSolverPCGSim3
from g2opy.g2o import LinearSolverPCGX
from g2opy.g2o import MotionMeasurement
from g2opy.g2o import OdomConvert
from g2opy.g2o import OptimizableGraph
from g2opy.g2o import OptimizationAlgorithm
from g2opy.g2o import OptimizationAlgorithmDogleg
from g2opy.g2o import OptimizationAlgorithmGaussNewton
from g2opy.g2o import OptimizationAlgorithmLevenberg
from g2opy.g2o import OptimizationAlgorithmProperty
from g2opy.g2o import OptimizationAlgorithmWithHessian
from g2opy.g2o import Parameter
from g2opy.g2o import ParameterCamera
from g2opy.g2o import ParameterSE2Offset
from g2opy.g2o import ParameterSE3Offset
from g2opy.g2o import ParameterStereoCamera
from g2opy.g2o import PyBlockSolverBase
from g2opy.g2o import Quaternion
from g2opy.g2o import RegisterOptimizationAlgorithmProxy
from g2opy.g2o import RobustKernelCauchy
from g2opy.g2o import RobustKernelDCS
from g2opy.g2o import RobustKernelFair
from g2opy.g2o import RobustKernelGemanMcClure
from g2opy.g2o import RobustKernelHuber
from g2opy.g2o import RobustKernelPseudoHuber
from g2opy.g2o import RobustKernelSaturated
from g2opy.g2o import RobustKernelScaleDelta
from g2opy.g2o import RobustKernelTukey
from g2opy.g2o import RobustKernelWelsch
from g2opy.g2o import Rotation2d
from g2opy.g2o import SBACam
from g2opy.g2o import SE2
from g2opy.g2o import SE3Quat
from g2opy.g2o import Sim3
from g2opy.g2o import Solver
from g2opy.g2o import SparseBlockMatrixX
from g2opy.g2o import SparseOptimizer
from g2opy.g2o import SparseOptimizerTerminateAction
from g2opy.g2o import TransformTraits
from g2opy.g2o import UniformCostFunction
from g2opy.g2o import VelocityMeasurement
from g2opy.g2o import VertexCam
from g2opy.g2o import VertexIntrinsics
from g2opy.g2o import VertexOdomDifferentialParams
from g2opy.g2o import VertexPointXY
from g2opy.g2o import VertexPointXYZ
from g2opy.g2o import VertexSBAPointXYZ
from g2opy.g2o import VertexSCam
from g2opy.g2o import VertexSE2
from g2opy.g2o import VertexSE3
from g2opy.g2o import VertexSE3Expmap
from g2opy.g2o import VertexSim3Expmap
from g2opy.g2o import contrib
import os as os
import sys as sys
from . import g2o
__all__ = ['AbstractOptimizationAlgorithmCreator', 'Affine', 'AffineCompact', 'AngleAxis', 'BaseBinaryEdge_1_double_VertexCam_VertexCam', 'BaseBinaryEdge_1_double_VertexSE2_VertexPointXY', 'BaseBinaryEdge_2_Vector2D_VertexPointXY_VertexPointXY', 'BaseBinaryEdge_2_Vector2D_VertexSBAPointXYZ_VertexCam', 'BaseBinaryEdge_2_Vector2D_VertexSBAPointXYZ_VertexSE3Expmap', 'BaseBinaryEdge_2_Vector2D_VertexSBAPointXYZ_VertexSim3Expmap', 'BaseBinaryEdge_2_Vector2D_VertexSE2_VertexPointXY', 'BaseBinaryEdge_3_EdgeGICP_VertexSE3_VertexSE3', 'BaseBinaryEdge_3_SE2_VertexSE2_VertexSE2', 'BaseBinaryEdge_3_Vector3D_VertexPointXYZ_VertexPointXYZ', 'BaseBinaryEdge_3_Vector3D_VertexSBAPointXYZ_VertexCam', 'BaseBinaryEdge_3_Vector3D_VertexSBAPointXYZ_VertexSCam', 'BaseBinaryEdge_3_Vector3D_VertexSBAPointXYZ_VertexSE3Expmap', 'BaseBinaryEdge_3_Vector3D_VertexSE3_VertexPointXYZ', 'BaseBinaryEdge_6_Isometry3D_VertexSE3_VertexSE3', 'BaseBinaryEdge_6_SE3Quat_VertexCam_VertexCam', 'BaseBinaryEdge_6_SE3Quat_VertexSE3Expmap_VertexSE3Expmap', 'BaseBinaryEdge_7_Sim3_VertexSim3Expmap_VertexSim3Expmap', 'BaseEdge_1_double', 'BaseEdge_2_Vector2D', 'BaseEdge_3_EdgeGICP', 'BaseEdge_3_SE2', 'BaseEdge_3_Vector3D', 'BaseEdge_3_VelocityMeasurement', 'BaseEdge_4_Vector4D', 'BaseEdge_6_Isometry3D', 'BaseEdge_6_SE3Quat', 'BaseEdge_7_Sim3', 'BaseMultiEdge_2_Vector2D', 'BaseMultiEdge_3_SE2', 'BaseMultiEdge_3_Vector3D', 'BaseMultiEdge_3_VelocityMeasurement', 'BaseMultiEdge_4_Vector4D', 'BaseMultiEdge_6_SE3Quat', 'BaseRobustKernel', 'BaseUnaryEdgeBaseUnaryEdge_2_Vector2D_VertexSE3Expmap', 'BaseUnaryEdgeBaseUnaryEdge_3_Vector3D_VertexSE3Expmap', 'BaseUnaryEdge_2_Vector2D_VertexSE2', 'BaseUnaryEdge_3_SE2_VertexSE2', 'BaseUnaryEdge_6_Isometry3D_VertexSE3', 'BaseVertex_1_double', 'BaseVertex_2_Vector2D', 'BaseVertex_3_SE2', 'BaseVertex_3_Vector3D', 'BaseVertex_4_Vector5d', 'BaseVertex_6_Isometry3D', 'BaseVertex_6_SBACam', 'BaseVertex_6_SE3Quat', 'BaseVertex_7_Sim3', 'BlockSolverBase', 'BlockSolverSE2', 'BlockSolverSE3', 'BlockSolverSim3', 'BlockSolverX', 'CameraParameters', 'DynamicBaseEdge_VectorXD', 'DynamicBaseMultiEdge_VectorXD', 'EdgeGICP', 'EdgeInverseSim3ProjectXYZ', 'EdgeNormal', 'EdgePointXY', 'EdgePointXYZ', 'EdgeProjectP2MC', 'EdgeProjectP2MCRight', 'EdgeProjectP2MC_Intrinsics', 'EdgeProjectP2SC', 'EdgeProjectPSI2UV', 'EdgeProjectXYZ2UV', 'EdgeProjectXYZ2UVU', 'EdgeSBACam', 'EdgeSBAScale', 'EdgeSE2', 'EdgeSE2LotsOfXY', 'EdgeSE2OdomDifferentialCalib', 'EdgeSE2Offset', 'EdgeSE2PointXY', 'EdgeSE2PointXYBearing', 'EdgeSE2PointXYCalib', 'EdgeSE2PointXYOffset', 'EdgeSE2Prior', 'EdgeSE2SensorCalib', 'EdgeSE2TwoPointsXY', 'EdgeSE2XYPrior', 'EdgeSE3', 'EdgeSE3Expmap', 'EdgeSE3LotsOfXYZ', 'EdgeSE3Offset', 'EdgeSE3PointXYZ', 'EdgeSE3PointXYZDepth', 'EdgeSE3PointXYZDisparity', 'EdgeSE3Prior', 'EdgeSE3ProjectXYZ', 'EdgeSE3ProjectXYZOnlyPose', 'EdgeSim3', 'EdgeSim3ProjectXYZ', 'EdgeStereoSE3ProjectXYZ', 'EdgeStereoSE3ProjectXYZOnlyPose', 'Edge_V_V_GICP', 'Edge_XYZ_VSC', 'EstimatePropagator', 'EstimatePropagatorCost', 'EstimatePropagatorCostOdometry', 'G2OBatchStatistics', 'HyperDijkstra', 'HyperGraph', 'HyperGraphAction', 'Isometry', 'Isometry2d', 'Isometry3d', 'JacobianWorkspace', 'LinearSolverCSparseSE2', 'LinearSolverCSparseSE3', 'LinearSolverCSparseSim3', 'LinearSolverCSparseX', 'LinearSolverCholmodSE2', 'LinearSolverCholmodSE3', 'LinearSolverCholmodSim3', 'LinearSolverCholmodX', 'LinearSolverDenseSE2', 'LinearSolverDenseSE3', 'LinearSolverDenseSim3', 'LinearSolverDenseX', 'LinearSolverEigenSE2', 'LinearSolverEigenSE3', 'LinearSolverEigenSim3', 'LinearSolverEigenX', 'LinearSolverPCGSE2', 'LinearSolverPCGSE3', 'LinearSolverPCGSim3', 'LinearSolverPCGX', 'MotionMeasurement', 'OdomConvert', 'OptimizableGraph', 'OptimizationAlgorithm', 'OptimizationAlgorithmDogleg', 'OptimizationAlgorithmGaussNewton', 'OptimizationAlgorithmLevenberg', 'OptimizationAlgorithmProperty', 'OptimizationAlgorithmWithHessian', 'Parameter', 'ParameterCamera', 'ParameterSE2Offset', 'ParameterSE3Offset', 'ParameterStereoCamera', 'Projective', 'PyBlockSolverBase', 'Quaternion', 'RegisterOptimizationAlgorithmProxy', 'RobustKernelCauchy', 'RobustKernelDCS', 'RobustKernelFair', 'RobustKernelGemanMcClure', 'RobustKernelHuber', 'RobustKernelPseudoHuber', 'RobustKernelSaturated', 'RobustKernelScaleDelta', 'RobustKernelTukey', 'RobustKernelWelsch', 'Rotation2d', 'SBACam', 'SE2', 'SE3Quat', 'Sim3', 'Solver', 'SparseBlockMatrixX', 'SparseOptimizer', 'SparseOptimizerTerminateAction', 'TransformTraits', 'UniformCostFunction', 'VelocityMeasurement', 'VertexCam', 'VertexIntrinsics', 'VertexOdomDifferentialParams', 'VertexPointXY', 'VertexPointXYZ', 'VertexSBAPointXYZ', 'VertexSCam', 'VertexSE2', 'VertexSE3', 'VertexSE3Expmap', 'VertexSim3Expmap', 'contrib', 'current_dir', 'g2o', 'os', 'sys']
Affine: g2o.TransformTraits  # value = TransformTraits.Affine
AffineCompact: g2o.TransformTraits  # value = TransformTraits.AffineCompact
Isometry: g2o.TransformTraits  # value = TransformTraits.Isometry
Projective: g2o.TransformTraits  # value = TransformTraits.Projective
current_dir: str = '/miniconda/lib/python3.9/site-packages/g2opy'
